eureka:
  client:
    service-url:
      defaultZone: http://euk1.com:7001/eureka/
server:
  port: 60 #7001
spring:
  application:
    name: provider
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
