eureka:
  client:
    service-url:
      defaultZone: http://euk1.com:7001/eureka/
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: euk1.com #euk1.com
server:
  port: 7001 #7001
spring:
  security:
    user:
      name: milelu
      password: 123
